from dataclasses import dataclass

from .contributor import ContributionPlan
from .execution import ExecutionArtifact
from .github_writer import GitHubRepositoryWriter


@dataclass(frozen=True)
class PublishResult:
    repository: str
    branch: str
    pull_request_number: int


class ContributionPublisher:
    def __init__(self, writer: GitHubRepositoryWriter, base_branch: str = "main") -> None:
        self.writer = writer
        self.base_branch = base_branch

    @staticmethod
    def _body(plan: ContributionPlan, body: str) -> str:
        summary = body.strip() or "Implementation generated by DevForge Contributor."
        return f"{summary}\n\n## DevForge task\n\n- Task: `{plan.task_key}`\n- Issue: #{plan.issue_number}\n\nCloses #{plan.issue_number}"

    def publish(
        self,
        plan: ContributionPlan,
        base_sha: str,
        branch: str,
        files: dict[str, str],
        title: str | None = None,
        body: str = "",
        publish_repository: str | None = None,
    ) -> PublishResult:
        publish_repository = publish_repository or plan.repository
        self.writer.create_branch(publish_repository, branch, base_sha)
        for path, content in files.items():
            self.writer.commit_file(
                publish_repository, branch, path, content, f"feat: implement issue #{plan.issue_number}"
            )
        pr_number = self.writer.create_draft_pr(
            plan.repository,
            branch,
            self.base_branch,
            title or plan.objective,
            self._body(plan, body),
            head_repository=publish_repository,
        )
        return PublishResult(plan.repository, branch, pr_number)

    def publish_artifact(
        self,
        artifact: ExecutionArtifact,
        base_sha: str,
        branch: str,
        title: str | None = None,
        body: str = "",
        publish_repository: str | None = None,
    ) -> PublishResult:
        return self.publish(artifact.plan, base_sha, branch, artifact.files, title, body, publish_repository)
